#!/usr/bin/env node
// Precomputes the overbooking surfaces shown in section 4 of cargorm.html.
// Uses the exact engine embedded in cargorm.html (between the crm-engine markers), so page and data can't drift apart.
// Run from the repo root:  node scripts/cargorm/precompute.js
// Reads assets/data/cargorm.json, writes assets/data/cargorm-overbooking.json. Takes a minute or two.
"use strict";
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..", "..");
const html = fs.readFileSync(path.join(root, "cargorm.html"), "utf8");
const m = html.match(/\/\/ <crm-engine>([\s\S]*?)\/\/ <\/crm-engine>/);
if (!m) throw new Error("engine markers not found in cargorm.html");
const CRM = new Function(m[1] + "\nreturn CRM;")();
const data = JSON.parse(fs.readFileSync(path.join(root, "assets/data/cargorm.json"), "utf8"));

const FLIGHTS = { belly: 1000, freighter: 300 }, SEED0 = 1000001;
const grid = [];
for (let i = 0; i <= 12; i++) grid.push(Math.round(i * 5) / 100);

const cells = {};
const t0 = Date.now();
for (const ac of data.aircraft) for (const dem of data.demand) for (const vr of data.variability) {
  const M = CRM.model(data, ac.key, dem.key, vr.key);
  const flights = [];
  const NF = FLIGHTS[ac.key] || 300;
  for (let f = 0; f < NF; f++) flights.push(CRM.genFlight(M, SEED0 + f * 7919));
  const out = { rev: [], offKg: [], offN: [], lfW: [], lfV: [] };
  for (const ow of grid) for (const ov of grid) {
    let rev = 0, offKg = 0, offN = 0, lfW = 0, lfV = 0;
    for (const reqs of flights) {
      const r = CRM.simFlight(M, reqs, "bp", ow, ov, false);
      rev += r.rev; offKg += r.offKg; offN += r.offN; lfW += r.carW / M.W; lfV += r.carV / M.V;
    }
    out.rev.push(Math.round(rev / NF));
    out.offKg.push(Math.round(offKg / NF));
    out.offN.push(Math.round(offN / NF * 100) / 100);
    out.lfW.push(Math.round(lfW / NF * 1000) / 1000);
    out.lfV.push(Math.round(lfV / NF * 1000) / 1000);
  }
  cells[ac.key + "|" + dem.key + "|" + vr.key] = out;
  console.log(ac.key, dem.key, vr.key, ((Date.now() - t0) / 1000).toFixed(1) + "s");
}

const result = {
  about: "Bid-price policy, average per flight over " + FLIGHTS.belly + " (belly) or " + FLIGHTS.freighter + " (freighter) simulated flights for each pair of overbooking levels. Index = iWeight * " + grid.length + " + iVolume. Generated by scripts/cargorm/precompute.js from cargorm.json.",
  generated: new Date().toISOString().slice(0, 10),
  flights: FLIGHTS,
  seed: SEED0,
  grid: grid,
  cells: cells
};
fs.writeFileSync(path.join(root, "assets/data/cargorm-overbooking.json"), JSON.stringify(result));
console.log("wrote assets/data/cargorm-overbooking.json");
