#!/usr/bin/env node
// Precomputes section 4 of freighterrotation.html: every rotation from every home region, with and without
// fifth-freedom rights, over the page's seeded year of demand.
// Uses the exact engine embedded in freighterrotation.html (between the fr-engine markers), so page and data can't drift apart.
// Run from the repo root:  node scripts/freighterrotation/precompute.js
// Reads assets/data/freighterrotation.json, writes assets/data/freighterrotation-rotations.json. Takes a few seconds.
// Prints the best rotation of each type for every home, as a check on the numbers.
"use strict";
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..", "..");
const html = fs.readFileSync(path.join(root, "freighterrotation.html"), "utf8");
const m = html.match(/\/\/ <fr-engine>([\s\S]*?)\/\/ <\/fr-engine>/);
if (!m) throw new Error("engine markers not found in freighterrotation.html");
const FR = new Function(m[1] + "\nreturn FR;")();
const data = JSON.parse(fs.readFileSync(path.join(root, "assets/data/freighterrotation.json"), "utf8"));

const weeks = FR.year(data, data.seed);
const r0 = (v) => Math.round(v), r2 = (v) => Math.round(v * 100) / 100, r3 = (v) => Math.round(v * 1000) / 1000;
const code = (k) => FR.region(data, k).code;
const homes = {};
const t0 = Date.now();
for (const reg of data.regions) {
  const home = reg.key, rots = FR.rotations(data, home);
  homes[home] = {};
  for (const fifth of [true, false]) {
    homes[home][fifth ? "on" : "off"] = rots.map((r) => {
      const e = FR.best(data, r.stops, { fifth }, weeks);
      return { id: r.id, type: r.type, stops: r.stops, contrib: r0(e.contrib), rev: r0(e.rev), cost: r0(e.cost),
        bh: r2(e.bhWeek), freq: r2(e.freq), fmax: r2(e.fmax), lf: r3(e.lf), costPerBH: r0(e.costPerBH) };
    }).sort((a, b) => b.contrib - a.contrib);
  }
  for (const k of ["on", "off"]) {
    const line = ["shuttle", "triangle", "rtw"].map((t) => {
      const b = homes[home][k].find((x) => x.type === t);
      return b ? t + " " + b.stops.map(code).join("-") + " $" + Math.round(b.contrib / 1000) + "k" : t + " none";
    }).join(" | ");
    console.log(reg.code, "fifth freedom " + k.padEnd(3), line);
  }
}

const result = {
  about: "Every rotation from every home region, with (on) and without (off) fifth-freedom rights: weekly averages over the seeded year of demand in freighterrotation.json, at the weekly frequency that earns the most. Generated by scripts/freighterrotation/precompute.js.",
  generated: new Date().toISOString().slice(0, 10),
  seed: data.seed,
  homes: homes
};
fs.writeFileSync(path.join(root, "assets/data/freighterrotation-rotations.json"), JSON.stringify(result));
console.log("wrote assets/data/freighterrotation-rotations.json in " + ((Date.now() - t0) / 1000).toFixed(1) + "s");
